//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace family.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_pt {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_pt() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("family.Resx.AppResources.pt", typeof(AppResources_pt).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HttpRequestException {
            get {
                return ResourceManager.GetString("HttpRequestException", resourceCulture);
            }
        }
        
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        internal static string UnEpectedError {
            get {
                return ResourceManager.GetString("UnEpectedError", resourceCulture);
            }
        }
        
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        internal static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        internal static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        internal static string TrackLimitReached {
            get {
                return ResourceManager.GetString("TrackLimitReached", resourceCulture);
            }
        }
        
        internal static string RastrearDispositivoSucesso {
            get {
                return ResourceManager.GetString("RastrearDispositivoSucesso", resourceCulture);
            }
        }
        
        internal static string LoginSenhaInvalido {
            get {
                return ResourceManager.GetString("LoginSenhaInvalido", resourceCulture);
            }
        }
        
        internal static string pontocontrole_sucessocadastro {
            get {
                return ResourceManager.GetString("pontocontrole_sucessocadastro", resourceCulture);
            }
        }
        
        internal static string pontocontrole_errocadastro {
            get {
                return ResourceManager.GetString("pontocontrole_errocadastro", resourceCulture);
            }
        }
        
        internal static string pontocontrole_sucessoalteracao {
            get {
                return ResourceManager.GetString("pontocontrole_sucessoalteracao", resourceCulture);
            }
        }
        
        internal static string CompraRealizada {
            get {
                return ResourceManager.GetString("CompraRealizada", resourceCulture);
            }
        }
        
        internal static string ServicoPago {
            get {
                return ResourceManager.GetString("ServicoPago", resourceCulture);
            }
        }
        
        internal static string pontocontrole_erroalteracao {
            get {
                return ResourceManager.GetString("pontocontrole_erroalteracao", resourceCulture);
            }
        }
        
        internal static string pontocontrole_sucessoexcluido {
            get {
                return ResourceManager.GetString("pontocontrole_sucessoexcluido", resourceCulture);
            }
        }
        
        internal static string pontocontrole_erroexcluido {
            get {
                return ResourceManager.GetString("pontocontrole_erroexcluido", resourceCulture);
            }
        }
        
        internal static string PositionNotFound {
            get {
                return ResourceManager.GetString("PositionNotFound", resourceCulture);
            }
        }
        
        internal static string latitudelongitudenaoencontrados {
            get {
                return ResourceManager.GetString("latitudelongitudenaoencontrados", resourceCulture);
            }
        }
        
        internal static string ancora_criacaoerro {
            get {
                return ResourceManager.GetString("ancora_criacaoerro", resourceCulture);
            }
        }
        
        internal static string ancora_desativacaoerro {
            get {
                return ResourceManager.GetString("ancora_desativacaoerro", resourceCulture);
            }
        }
        
        internal static string invalidlogin {
            get {
                return ResourceManager.GetString("invalidlogin", resourceCulture);
            }
        }
        
        internal static string emailalreadyregistered {
            get {
                return ResourceManager.GetString("emailalreadyregistered", resourceCulture);
            }
        }
        
        internal static string nocallcenteravailable {
            get {
                return ResourceManager.GetString("nocallcenteravailable", resourceCulture);
            }
        }
        
        internal static string CadastrarUsuarioSucesso {
            get {
                return ResourceManager.GetString("CadastrarUsuarioSucesso", resourceCulture);
            }
        }
        
        internal static string ComandoEnviado {
            get {
                return ResourceManager.GetString("ComandoEnviado", resourceCulture);
            }
        }
        
        internal static string AncoraCriadaSucesso {
            get {
                return ResourceManager.GetString("AncoraCriadaSucesso", resourceCulture);
            }
        }
        
        internal static string AncoraDesativada {
            get {
                return ResourceManager.GetString("AncoraDesativada", resourceCulture);
            }
        }
        
        internal static string UseEmailPass {
            get {
                return ResourceManager.GetString("UseEmailPass", resourceCulture);
            }
        }
        
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string AppWithChip {
            get {
                return ResourceManager.GetString("AppWithChip", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string EmailPlease {
            get {
                return ResourceManager.GetString("EmailPlease", resourceCulture);
            }
        }
        
        internal static string PassworPlease {
            get {
                return ResourceManager.GetString("PassworPlease", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string TrackDevice {
            get {
                return ResourceManager.GetString("TrackDevice", resourceCulture);
            }
        }
        
        internal static string TrackDeviceAdmin {
            get {
                return ResourceManager.GetString("TrackDeviceAdmin", resourceCulture);
            }
        }
        
        internal static string TrackDeviceNotAdmin {
            get {
                return ResourceManager.GetString("TrackDeviceNotAdmin", resourceCulture);
            }
        }
        
        internal static string TrackDeviceEndText {
            get {
                return ResourceManager.GetString("TrackDeviceEndText", resourceCulture);
            }
        }
        
        internal static string PanicAlert {
            get {
                return ResourceManager.GetString("PanicAlert", resourceCulture);
            }
        }
        
        internal static string PanicAlertSendExplanation {
            get {
                return ResourceManager.GetString("PanicAlertSendExplanation", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        internal static string Historic {
            get {
                return ResourceManager.GetString("Historic", resourceCulture);
            }
        }
        
        internal static string Checkpoint {
            get {
                return ResourceManager.GetString("Checkpoint", resourceCulture);
            }
        }
        
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        internal static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
        
        internal static string GettingAddress {
            get {
                return ResourceManager.GetString("GettingAddress", resourceCulture);
            }
        }
        
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        internal static string AnchorCreated {
            get {
                return ResourceManager.GetString("AnchorCreated", resourceCulture);
            }
        }
        
        internal static string AnchorDisabled {
            get {
                return ResourceManager.GetString("AnchorDisabled", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string LoadMorePositions {
            get {
                return ResourceManager.GetString("LoadMorePositions", resourceCulture);
            }
        }
        
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        internal static string DatePosition {
            get {
                return ResourceManager.GetString("DatePosition", resourceCulture);
            }
        }
        
        internal static string DateUpdate {
            get {
                return ResourceManager.GetString("DateUpdate", resourceCulture);
            }
        }
        
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        internal static string Ignition {
            get {
                return ResourceManager.GetString("Ignition", resourceCulture);
            }
        }
        
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        internal static string GprsSignal {
            get {
                return ResourceManager.GetString("GprsSignal", resourceCulture);
            }
        }
        
        internal static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        internal static string BlockPassword {
            get {
                return ResourceManager.GetString("BlockPassword", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string BlockAlert {
            get {
                return ResourceManager.GetString("BlockAlert", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Exclusion {
            get {
                return ResourceManager.GetString("Exclusion", resourceCulture);
            }
        }
        
        internal static string ConfirmExclusionCheckPoint {
            get {
                return ResourceManager.GetString("ConfirmExclusionCheckPoint", resourceCulture);
            }
        }
        
        internal static string AddCheckPoint {
            get {
                return ResourceManager.GetString("AddCheckPoint", resourceCulture);
            }
        }
        
        internal static string Salve {
            get {
                return ResourceManager.GetString("Salve", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        internal static string ErrorCepEmpty {
            get {
                return ResourceManager.GetString("ErrorCepEmpty", resourceCulture);
            }
        }
        
        internal static string ErrorCepInvalid {
            get {
                return ResourceManager.GetString("ErrorCepInvalid", resourceCulture);
            }
        }
        
        internal static string ErrorTelefoneEmpty {
            get {
                return ResourceManager.GetString("ErrorTelefoneEmpty", resourceCulture);
            }
        }
        
        internal static string ErrorEmailEmpty {
            get {
                return ResourceManager.GetString("ErrorEmailEmpty", resourceCulture);
            }
        }
        
        internal static string ErrorEmailInvalid {
            get {
                return ResourceManager.GetString("ErrorEmailInvalid", resourceCulture);
            }
        }
        
        internal static string ErrorPasswordsEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordsEmpty", resourceCulture);
            }
        }
        
        internal static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        internal static string ErrorAddressEmpty {
            get {
                return ResourceManager.GetString("ErrorAddressEmpty", resourceCulture);
            }
        }
        
        internal static string PanicSend {
            get {
                return ResourceManager.GetString("PanicSend", resourceCulture);
            }
        }
        
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        internal static string ProximaRevisao {
            get {
                return ResourceManager.GetString("ProximaRevisao", resourceCulture);
            }
        }
        
        internal static string ProximaTrocaOleo {
            get {
                return ResourceManager.GetString("ProximaTrocaOleo", resourceCulture);
            }
        }
        
        internal static string RodizioPneu {
            get {
                return ResourceManager.GetString("RodizioPneu", resourceCulture);
            }
        }
        
        internal static string Seguro {
            get {
                return ResourceManager.GetString("Seguro", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SomenteNumero {
            get {
                return ResourceManager.GetString("SomenteNumero", resourceCulture);
            }
        }
        
        internal static string MaintenanceSave {
            get {
                return ResourceManager.GetString("MaintenanceSave", resourceCulture);
            }
        }
        
        internal static string CancelarComando {
            get {
                return ResourceManager.GetString("CancelarComando", resourceCulture);
            }
        }
        
        internal static string CancelarComandoSucesso {
            get {
                return ResourceManager.GetString("CancelarComandoSucesso", resourceCulture);
            }
        }
        
        internal static string ErroSuporte {
            get {
                return ResourceManager.GetString("ErroSuporte", resourceCulture);
            }
        }
        
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        internal static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        internal static string NotCharging {
            get {
                return ResourceManager.GetString("NotCharging", resourceCulture);
            }
        }
        
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        internal static string ClienteBloqueado {
            get {
                return ResourceManager.GetString("ClienteBloqueado", resourceCulture);
            }
        }
        
        internal static string ClienteDesativado {
            get {
                return ResourceManager.GetString("ClienteDesativado", resourceCulture);
            }
        }
        
        internal static string Configurar {
            get {
                return ResourceManager.GetString("Configurar", resourceCulture);
            }
        }
        
        internal static string DayTime {
            get {
                return ResourceManager.GetString("DayTime", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string HoraFinalInvalida {
            get {
                return ResourceManager.GetString("HoraFinalInvalida", resourceCulture);
            }
        }
        
        internal static string HoraInicialInvalida {
            get {
                return ResourceManager.GetString("HoraInicialInvalida", resourceCulture);
            }
        }
        
        internal static string HoraInicialIgualMaior {
            get {
                return ResourceManager.GetString("HoraInicialIgualMaior", resourceCulture);
            }
        }
        
        internal static string SelecioneDiaSemana {
            get {
                return ResourceManager.GetString("SelecioneDiaSemana", resourceCulture);
            }
        }
        
        internal static string HoraInicialFinalInvalida {
            get {
                return ResourceManager.GetString("HoraInicialFinalInvalida", resourceCulture);
            }
        }
        
        internal static string ExibeStreetView {
            get {
                return ResourceManager.GetString("ExibeStreetView", resourceCulture);
            }
        }
        
        internal static string StreetView {
            get {
                return ResourceManager.GetString("StreetView", resourceCulture);
            }
        }
        
        internal static string Gps {
            get {
                return ResourceManager.GetString("Gps", resourceCulture);
            }
        }
        
        internal static string GpsOpenSettings {
            get {
                return ResourceManager.GetString("GpsOpenSettings", resourceCulture);
            }
        }
        
        internal static string GpsSettings {
            get {
                return ResourceManager.GetString("GpsSettings", resourceCulture);
            }
        }
        
        internal static string Hibrido {
            get {
                return ResourceManager.GetString("Hibrido", resourceCulture);
            }
        }
        
        internal static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        internal static string Satelite {
            get {
                return ResourceManager.GetString("Satelite", resourceCulture);
            }
        }
        
        internal static string Terreno {
            get {
                return ResourceManager.GetString("Terreno", resourceCulture);
            }
        }
        
        internal static string Trafego {
            get {
                return ResourceManager.GetString("Trafego", resourceCulture);
            }
        }
        
        internal static string MapaPadrao {
            get {
                return ResourceManager.GetString("MapaPadrao", resourceCulture);
            }
        }
        
        internal static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
    }
}
